### ISSUE TITLE
How to exclude node_modules directory from commit?

### ISSUE THREAD

**Issue by R0quef0rt** [semantic-release/git#107]
Hello,

Great project. I'm very impressed with how well it works for me.

I am trying to ignore the "node_submodules" directory when committing to git, but I cannot figure out how to do it. Is this even a good practice? I feel like I shouldn't be committing 50mb of files to source control - but this appears to be the default behavior.

I tried to ignore this directory in my "assets" setting, as well as my .gitignore file. Unfortunately, that doesn't seem to work. Can somebody point me in the right direction?

Here is my package.json config: https://pastebin.com/7hzjZD8y

And here is a snip of my debug output:

```
[06:14:35] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[06:14:35] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[06:14:35] [semantic-release] [@semantic-release/changelog] › ℹ  Update /builds/cyberdefenses/build/CHANGELOG.md
[06:14:35] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[06:14:35] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
2018-12-19T06:14:35.655Z semantic-release:git globed assets: []
[06:14:35] [semantic-release] [@semantic-release/git] › ℹ  Found 7846 file(s) to commit
2018-12-19T06:14:36.680Z semantic-release:git add file to git index { stdout: '',
  stderr: '',
  code: 0,
  failed: false,
  killed: false,
  signal: null,
  cmd: 'git add --force --ignore-errors node_modules/.bin/JSONStream node_modules/.bin/atob node_modules/.bin/cdl node_modules/.bin/conventional-changelog-writer node_modules/.bin/conventional-commits-parser node_modules/.bin/esparse node_modules/.bin/esvalidate node_modules/.bin/handlebars node_modules/.bin/js-yaml node_modules/.bin/marked node_modules/.bin/mime node_modules/.bin/npm node_modules/.bin/npx node_modules/.bin/parse-github-url node_modules/.bin/rc node_modules/.bin/semantic-release node_modules/
```

Any help would be greatly appreciated.

Ryan

**Comment by pvdlg** [comment]
Your configuration for `assets` is different in `@semantic-release/git` and `@semantic-release/gitlab` which seems surprising. It probably not what you want.

In any case you overwrite both with `"assets": "dist/*.tgz"` which seems to match nothing in your repo. There is a bug where all files get retrieved in a case where a glob is defined in `assets` but doesn't match anything in the repo which is fixed in https://github.com/semantic-release/git/pull/108.

There is overall many problems with your configuration:
- You have 3 different configs for `assets` and the one that take precedence (`"dist/*.tgz"`) doesn't match anything
- You specify the plugins in `plugins` and  then overwrite each step with the same plugins in `analyzeCommits`, `verifyConditions`, `prepare`, `generateNotes`, `publish`, `success` and `fail`. That is unnecessary, confusing and overwrite every option you defined in the definitions in `plugins` 
- It seems you prefer to configure plugins option in their definition in `plugins`, however for `npmPublish` and `tarballDir` you do that at the global level, that seems inconsistent

Please read the [plugins documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md).

**Comment by R0quef0rt** [comment]
Thank you very much for the help, and with the extra suggestions regarding my other problems! I'm sure somebody will appreciate the PR, too!

This fixed all of my problems, and it cleared up a lot of the confusion I had, too. I just started using semantic-release ~24 hours ago, so I'm still trying to wrap my head around around everything. 

I really appreciate everything you've done!

Ryan
