### ISSUE TITLE
Question: how to work with husky precommit

### ISSUE THREAD

**Issue by nicosampler** [semantic-release/git#124]
I'm having a problem running, it was working well until I added a pre-commit task to run some linter validations and flow typechecker. I have this configuration in my `package.json`

```
"husky": {
    "hooks": {
      "pre-commit": "lint-staged && yarn flow"
    }
  },
```
running `yarn semantic-release` it start running well until it try to commit and push the `package.json` with the new generated version. at that moment I can see how the `pre-commit` task start but when it finishes without errors, the `semantic-releases` never resume.

I tried changing this: ` await execa('git', ['commit', '-m', message], execaOpts);`  to this: ` await execa('git', ['commit', '-m', message, '--no-verify'], execaOpts);` and it worked well because I'm preventing to run `husky`.

So, my questions is, how can I send the `--no-verify` flag when I run semantic-release? or how can I tell semantic-release to resume when the linters and flow finished without error?

**Comment by pvdlg** [comment]
The is no way to tell `@semantic-release/git` to add `--no-verify` and that's intended. If you have a pre-commit hook, that means you want to enforce it before committing, so that's a good thing to not allow committing code that won't pass your hook.

You can get more information about error message by running semantic-release with the `--debug` option.

In any case, if you want to enforce something (like valid flow type) with a pre-commit hook, you should make sure your code is compliant. If you are ok with code that is not compliant then don't use the pre-commit hook.
It doesn't seem to make sense to add a pre-commit hook and bypass it with `--no-verify`. If you don't want it, then don't add it.

**Comment by nicosampler** [comment]
totally agreed, but the problem is that the code does not have any errors, but semantic-release get stuck after pre-commit validations finished ok.

For example, if I run yarn flow and yarn lint, it pass well, immediately after, if I run yarn semantic-release, it never finishes, no error, not nothing.

**Comment by pvdlg** [comment]
Please provide the logs when running with `--debug`.
Please also make sure `lint-staged && yarn flow` doesn't errors out on your CI.

**Comment by jfairley** [comment]
@nicosampler `husky` won't run in CI by default, which is where `semantic-release` is _supposed_ to run also.

If you're trying to run a release locally, that's probably unsupported, first off, but otherwise, if you want to trick `husky`, you could try running like `CI=true yarn semantic-release`.

(Transitively, `husky` gets its info from [`ci-info`](https://github.com/watson/ci-info/blob/3141158a4f82772732bc5626d79621413cac6d41/index.js#L53).)

**Comment by nicosampler** [comment]
That's right, I had forgotten completely about `CI = true`, thx a lot for the reminder. Yes, I'm running `semantic-release` from my local right now.

**Comment by pvdlg** [comment]
Can this issue be closed then?

**Comment by nicosampler** [comment]
yes, thx!

**Comment by trentrand** [comment]
For what is worth, the answer provided by @jfairley absolutely does solve this issue; however, using `HUSKY_SKIP_INSTALL=1` (instead of `CI=true`) seems like a more appropriate solution.

https://github.com/typicode/husky/blob/master/README.md

**Comment by flo-sch** [comment]
On the same subject, husky v6 has removed `HUSKY_SKIP_HOOKS=1` but `HUSKY=0` can be used instead
