### ISSUE TITLE
[bug] premature git push in prepare step; should be in publish step instead

### ISSUE THREAD

**Issue by carmanchris31** [semantic-release/git#174]
#### Issue

This plugin performs a `git push` of the release commit during the `prepare` step which is premature. If the publish step fails, origin would have a release commit for a release that never actually occurred.

#### Expectation

The commit should not be pushed until the `publish` step. This aligns better with other plugins and helps prevent orphaned release artifacts (in this case, the release commit).

#### Example Scenario
I had a credentials issue so the `publish` step of the `@semantic-release/npm` plugin failed. Although I have `@semantic-release/git` _after_ `@semantic-release/npm` in my plugins list, `prepare` has already pushed the commit by this point.

As a result, when I fixed the credential issue through environment variables and re-ran the release job, semantic-release bailed out with the message "The local branch master is behind the remote one, therefore a new version won't be published." If the commit hadn't been pushed to remote already semantic-release would have been able to try again and release as normal.

**Comment by carmanchris31** [comment]
Related: https://github.com/semantic-release/semantic-release/issues/896

Wondering if there's a list of "things" that compete with saving pushes until publish, such as `apm` mentioned in that issue.

**Comment by pvdlg** [comment]
The `prepare` step was actually added just for the case of pushing commits to the remote repo.
The reason is that:
- We want the commit to be pushed before the tag is created so the updated files that we commit are included in the release
- We want to create the tag before the `publish` step as many plugins need the tag to exist on the remote repo to publish a release (apm, Github, Gitlab for example)

We won't change that as there is no other way to satisfies those constraints. 
As explained in semantic-release/semantic-release#896 we are aware that some rare situation can lead in partial releases that are difficult to recover from. Unfortunately there is no perfect solution for that as we don't have any way to rollback publication.

> I had a credentials issue so the publish step of the @semantic-release/npm plugin failed. Although I have @semantic-release/git after @semantic-release/npm in my plugins list, prepare has already pushed the commit by this point.

This is why we have a `verifyConditions` step that check your credential so you don't end up in that situation. You must have disabled them somehow. If you didn't and all the `verifyConditions` passed even though the credential were incorrect please open another bug and provide your logs.

**Comment by carmanchris31** [comment]
Thank you for the explanation. I do not have any verifyConditions disabled but I am using artifactory as the registry. I’ll look into seeing if there’s a way to validate the permissions against that and see how that compares to the method in this plugin.
