### ISSUE TITLE
verified signature

### ISSUE THREAD

**Issue by IamMHC** [semantic-release/git#175]
kindly add a verified signature for GitHub action

**Comment by pvdlg** [comment]
Can you clarify what this is issue is about? Is that a feature request?

Are you asking about that: https://github.com/semantic-release/git#gpg-signature ?

**Comment by IamMHC** [comment]
yes I ask about that but it's for Travis not for git hub action

**Comment by IamMHC** [comment]
semantic-release-bot does not commit with a verified signature

**Comment by pvdlg** [comment]
In order to sign the commits you need a GPG key on your CI where semantic-release runs. That means your CI has to provide a way to have the GPG key available in a secured fashion. It's dependent on your CI and not on this plugin.
I added some documentation for Travis as I happen to use it. But I'm won't research every CI out there to figure out how to achieve this. That said I'm open for a PR that would add this documentation for other CIs.

Regarding the link https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification#signature-verification-for-bots I think there is a misunderstanding there.

semantic-release-bot is a bot that belong to our organization and it just happens to be the default commiter name of the plugin (see https://github.com/semantic-release/git#environment-variables).
We are not going to provide the semantic-release-bot GPG key publicly!

If you want to sign your commits you will have to:
- Create your own bot or use whatever user you'd like and configure it with the `GIT_AUTHOR_NAME` environment variable
- Generate the GPG keys and make them available on your CI, import it on your CI and configure the CI git to sign commits with the configs `commit.gpgsign` and `user.signingkey`

I'll close this issue as it's CI related and out of scope of this plugin. As mentioned before we'll accept a PR with documentation to configure GPG keys on a specific CI, similar to the one we have for Travis.
