### ISSUE TITLE
use .gitignore to set the default assets value

### ISSUE THREAD

**Issue by oupala** [semantic-release/git#176]
The git plugin require to define the list of included assets to commit in a configuration file.

In fact, this list is already set in the `.gitignore` file.

So my proposal would be to use the `.gitignore` file to set the default assets value. This default value could be set to: all files except those listed in the `.gitignore` file.

Would this be a good idea?

**Comment by pvdlg** [comment]
> In fact, this list is already set in the `.gitignore` file.

Not really. `.gitignore` indicate the files you never want to be committed. That's not the same thing as "all the files that are not my releasable assets".

There is many cases (I'd argue most cases) where you don't want to commit all the modified files that are not in `.gitignore`:
- You want to push `package.json` and `CHANGELOG.md` but not the built assets as you don't want them on your repo
- Your build script produces some assets an then bundled them and you want to push only the bundle
- Your built assets are in the `.gitignore` because you don't want to commit them from your local machine, but you still want to have semantic-release to commit them on release

So I don't think it would be a good idea to automatically commit everything that is not in `.gitignore`. We also want to allow committing files that are in the `.gitignore` (3rd example).

**Comment by oupala** [comment]
For all 3 examples, I think that we never want to commit build assets.

Build assets can be embedded in a GitHub or GitLab release, which is a purpose of the concept of a release in these tools. But this relies on the github and the gitlab plugin of semantic-release.

I still think that for the git plugin, we might *by default* want to commit all modified files except those listed in `.gitignore`.

We're still able to commit a file listed in `.gitignore` by overriding the value of this parameter.

The [default value](https://github.com/semantic-release/git#options) of this parameter is:

> ['CHANGELOG.md', 'package.json', 'package-lock.json', 'npm-shrinkwrap.json']

**Comment by oupala** [comment]
My thoughs on your examples:

> - You want to push package.json and CHANGELOG.md but not the built assets as you don't want them on your repo

As you usually never want to commit build assets, you usually add them to your `.gitignore`.

> - Your build script produces some assets an then bundled them and you want to push only the bundle

As you usually never want to commit build assets bundles, you usually add them to your `.gitignore`.

> - Your built assets are in the .gitignore because you don't want to commit them from your local machine, but you still want to have semantic-release to commit them on release

The GitLab or GitHub plugin are there to handle this, not the git plugin.

Do you agree or is there something I did not catch?

**Comment by oupala** [comment]
Pull request #56 is about ignoring `.gitignore` file to set the list of assets. It has been explicityl designed to ignore `.gitignore` file while I'm asking for the exact opposite behavior.

I now understand why @pvdlg does not agree with me on this feature request. :wink:

**Comment by pvdlg** [comment]
This is not necessarily redundant with GitHub/GitLab release because not everybody uses GitLab or GitHub. There is also cases where the built assets have to be available from the Git repo.

As you saw in #56, we want to preserve the ability to have the build asset directory in the `.gitignore` and still be able to commit those files during a release. I think this use case is more common than wanting to commit everything that is not in `.gitignore`.

Finally we prefer to have users to be explicit about what to commit to avoid situation where one would forget to add something in `.gitignore` and end up having that committed. Basically we want to avoid relying on users configuring there `.gitignore` properly and  take them by surprise by committing things without their explicit consent (via configuration of `assets` option).

**Comment by oupala** [comment]
Well, I really don't now if this is common to commit build assets into the git repository. I consider it to be a bad habit. I would be very surprised if the usecase you're talking about (having the build asset directory in the .gitignore and still being able to commit those files during a release) is more common than wanting to commit everything that is not in `.gitignore`.

In fact, I think the debate is about [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration): I would advise to set as a convention the best practices and allow to set other practives by configuration.

We simply do not agree on what are the *best practices* and what are the *most common usecases*.

**Comment by pvdlg** [comment]
> Well, I really don't now if this is common to commit build assets into the git repository. I consider it to be a bad habit.
That's a fine opinion to have. However doing that is the whole point of this plugin...so if you consider it's a bad practice, why do you use this plugin in the first place and why do you open issues about it?
We don't want to force anyone to upload dist file to their repo, which is why this is implemented as a plugin that you can choose to use or not.

> I would be very surprised if the usecase you're talking about (having the build asset directory in the .gitignore and still being able to commit those files during a release) is more common than wanting to commit everything that is not in .gitignore.

I base that opinion on issues and support requests I get on the semantic-release repos. That's certainly a very incomplete set of data, but I think it's still more potent than the argument that the thing you want is what everyone else wants.

> In fact, I think the debate is about convention over configuration:
Making release is something very sensitive for obvious reasons. We don't want to do release related things based on arbitrary convention. We prefer to have an explicit consent of the user via configuration for those kind of things.
I don't want to have a semantic-release user accidentally committing sensitive data (such as keys used in deployment, an `.npmrc` file containing a token or any other temporary files containing authentication) to their repo because they forgot to add a file to `.gitignore`.

> I would advise to set as a convention the best practices and allow to set other practives by configuration.

This project is not the place to define and debate good practices. There is better area to do that: blog post, forums, conventions, specification committees, etc...When those are defined and agreed upon by a large part of the community we'll certainly help supporting them.
My personal goal for the semantic-release projects is to provide something useful to some people. If we start debating about people opinions regarding best practices it ends up being very distracting, prevent to move forward with new features, and generally boils down to a lot of comments along the lines of "such and such is **the** best practice because it's what **I** am doing".

**Comment by oupala** [comment]
I don't feel like establishing *what are the best practices*. I feel more like *following the best practices*.

But I do agree with you that issues are not the best place to discuss about it. Thanks for discussing it up to now.
