### ISSUE TITLE
generated commit message fails commitlint

### ISSUE THREAD

**Issue by skeggse** [semantic-release/git#209]
It's [possible](https://github.com/bee-queue/arena/runs/952014075?check_suite_focus=true) for the generated release notes to fail commitlint rules when included in the commit message verbatim, despite using the same preset in `release.config.js` as in `commitlint.config.js`. 

```
✖   footer's lines must not be longer than 100 characters [footer-max-line-length]

✖   found 1 problems, 0 warnings
```

This feels like something that either the git plugin or the generate-release-notes plugin should handle - thoughts?

**Comment by ScottChapman** [comment]
yea, I'm running into this as well. Stuck on it.
Did you figure out how to work around it?

**Comment by travi** [comment]
i missed this issue originally and it looks like the linked logs have expired. i assume commitlint is running in a git-hook, likely for the `pre-commit` event, would that be accurate? could you each describe how you have your hooks configured? keep in mind that semantic-release is intended to execute as part of your CI build, where tools like husky do not install the hooks.

could you also describe your goal a bit more? is the problem that the failure simply prevents the process from completing, or are you truly wanting the commit to pass linting? 

it might be reasonable for us to add the `--no-verify` flag to forcefully skip the hooks, but it would be better for the hooks to not be in play at all. 

however, if the desire is for the message to meet arbitrary lint rules, that would likely require more complexity than we are prepared to take on, especially since the presets can be modified on both the semantic-release and commitlint sides.

**Comment by ScottChapman** [comment]
No worries, just getting up to speed on how this all works. But your guess is right; pre-commit hook to verify commits.

Basically what's going on is that `commitlint` is configured to use `config-conventional` which is too strict with respect to line limitations.

I understand the proper fix is likely to pick a different one, or modify an existing one. But wouldn't mind an experts opinion on best practice. 

If the best practice would be to avoid the hook during this, how might I do that?

**Comment by travi** [comment]
> I understand the proper fix is likely to pick a different one, or modify an existing one.

i wouldnt say this is necessarily the proper fix. feel free to use whatever config you want for your team of humans as long as you are ok with automated tools like semantic-release not matching that convention exactly. the _best_ practice is to ensure that you are only running semantic-release in a ci environment and that you are using a tool like husky that [skips installation of the git hooks](https://github.com/typicode/husky/tree/master#ci-servers) in such an environment.

if you are simply experimenting locally in order to learn how semantic-release works, i recommend doing that experimentation in an environment similar to ci, so a project that doesnt have commitlint or git hooks configured. in the end, we recommend having a plan to move the release process to ci once you have learned from your experimentation.

**Comment by ScottChapman** [comment]
I think you can probably close this. 
Thanks!

**Comment by travi** [comment]
@skeggse @ismay does this explanation cover your use cases?

**Comment by ismay** [comment]
> @skeggse @ismay does this explanation cover your use cases?

Yup it does, thanks!

**Comment by skeggse** [comment]
I believe I was running into an entirely different issue (no git hooks, for starters). I'll circle back in a bit.

**Comment by ScottChapman** [comment]
actually, having a `--no-verify` option would be useful. Provides a fail-safe mechanism to skip the hook

**Comment by skeggse** [comment]
I guess perhaps this is an overlapping use-case. I have commitlint configured to run in CI explicitly, which causes this problem. If there were an easy way to filter which commits should get linted, that'd help - but that's an issue for another project. If you're saying that the commits generated here should never get linted, then I guess that's the resolution here.

**Comment by ismay** [comment]
> @skeggse @ismay does this explanation cover your use cases?

Actually I ran into this again and it hasn't been solved as far as I'm concerned. I'm using pretty much the standard, recommended configuration and the release step is failing at the prepare step for the git plugin: https://github.com/ismay/stylelint-no-unsupported-browser-features/runs/2645662031#step:4:68

Since I'm not doing anything strange (I don't think so at least), I wouldn't expect the git plugin to fail my release.

**Comment by ismay** [comment]
Ok, so in the end I don't think it's an issue with this plugin. What caused the issue for me is that husky has changed its approach so that now it doesn't skip installation automatically on CI and thus it was triggering linting of commit messages on CI. See the issue here: https://github.com/typicode/husky/issues/920

There are multiple ways to fix it, but what I did is add the `--ignore-scripts` flag to my `npm i` ([here](https://github.com/ismay/stylelint-no-unsupported-browser-features/commit/3f5d79762d282d88f5892cd56a42741f89d15547)). Hope that helps.

**Comment by molvqingtai** [comment]
This solves my problem `npm ci --ignore-scripts`

**Comment by travi** [comment]
thank you all for continuing to provide feedback here. it sounds like it has been helpful to some who have found this issue. 

it is also helpful to us, as maintainers, to understand if we are meeting expectations approproiately. it sounds like there is agreement that this is not a problem with the git pluging and that it is best to prevent commitlint from running on ci for these commits.

i'm going to close this issue at this point, but please feel free to additional comments that you feel would be helpful for the community.
