### ISSUE TITLE
Command failed: git push --tags

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [semantic-release/git#34]
https://circleci.com/gh/thunder-js/common-js/54

Hi! I've generated my Github Personal Token (with full access to everything btw) and added an env var called GH_TOKEN to CircleCI 2.0
Still, it says that the "The key you are authenticating with has been marked as read only."

**Comment by pvdlg** [comment]
Do you have ssh set up on CircleCI? If yes semantic-release will use those instead of GH_TOKEN.

So if the ssh keys you have on CircleCI do not allow to push it will fail. Either set up ssh keys that allow to push or remove your ssh key so GH_TOKEN will be used.

See https://stackoverflow.com/questions/33467474/github-authenticates-but-will-not-allow-code-push

**Comment by rafaelcorreiapoli** [comment]
It worked! Thanks
I added a key to CircleCI that allowed it to push to github
Thanks for the quick response!
