### ISSUE TITLE
`assets` does not support files from parent directories

### ISSUE THREAD

**Issue by loderunner** [semantic-release/git#389]
I am using @semantic-release/git in a repo with [NPM workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces). This means that while each workspace has its own `package.json` file, but the `package-lock.json` file is shared by all workspaces.

Here is an example project structure:

```
├── package-lock.json
├── workspace-1
│   ├── package.json
│   └── release.config.js
└── workspace-2
    ├── package.json
    └── release.config.js
```

Each workspace has its own semantic-release config.

I tried to use @semantic-release/git to add `package-lock.json` to assets with the following configuration:

```js
    [
      '@semantic-release/git',
      {
        assets: ['package.json', '../package-lock.json', 'CHANGELOG.md'],
      },
    ],
```

But since `prepare` uses [`getModifiedFiles`](https://github.com/semantic-release/git/blob/master/lib/prepare.js#L33), which in turn uses [`git ls-files`](https://github.com/semantic-release/git/blob/e84c6b049ac635b4587b758b669ed0ac45309d09/lib/git.js#L12) to find modified files to add to a commit, `../package-lock.json` cannot be included in the release commit.

Can it be possible to add this file while still running semantic-release from inside the workspace?

**Comment by loderunner** [comment]
I proposed a fix in #390 using `git rev-parse --show-toplevel` to find all modified files in the repo.

**Comment by travi** [comment]
as mentioned in the PR thread, this is not a use case that we have the capacity to consider at this point since semantic-release officially does not support monorepos.

**Comment by micchickenburger** [comment]
@travi I think this issue should be reopened.  There are numerous use cases that are not related to monorepos.  The trouble is that this plugin assumes `package.json` should be in the root project directory.  Consider the following directory structure (which I use a lot to keep my application code separate from CI, IaaC, and docker configurations):

```
├── README.md
├── CHANGELOG.md
└── src
    ├── package.json
    └── package-lock.json
    └── node_modules/
```

In this case, `@semantic-release/changelog` has no trouble at all creating `../CHANGELOG.md`.  `@semantic-release/git` just has trouble committing it because it's in the parent directory.
