### ISSUE TITLE
Can @semantic-release/git be used and not push the `package.json`

### ISSUE THREAD

**Issue by kopax** [semantic-release/git#50]
> However, the @semantic-release/git plugin can be used to push the updated package.json as well as other files to the Git repository.

We need that feature for the file, but we want to disable the push on release branch due to a conflicting issue on GitLab not allowing us to deploy page after the semantic-release.

See https://gitlab.com/gitlab-org/gitlab-ce/issues/39141

After readiing this documentation, I assume it is not possible to disable the commit message. Am I correct?

**Comment by pvdlg** [comment]
I'm not really sure what the problem is and how the different points are related....

As explained in [the documentation](https://github.com/semantic-release/git#options) if you don't want to push the `package.json` then just use the `assets` options to configure which assets you want to push.

Disabling the commit message is not possible as Git require each commit to have a message. You simply can't commit without a message. Even if it was possible I don't see why it would be useful to have commits without message.

If you want to disable the commit, then just don't use this plugin as its only goal is to commit files to the repo during releases.

**Comment by kopax** [comment]
> If you want to disable the commit, then just don't use this plugin as its only goal is to commit files to the repo during releases.

This is what I have done and it make sens. The issue with gitlab page is that it can't deploy page after that commit because the page needs to be on HEAD in order to succeed it's deployment.
