### ISSUE TITLE
Not including assets in release commit

### ISSUE THREAD

**Issue by dadamssg** [semantic-release/git#68]
I'm [playing around](https://github.com/dadamssg/react-testing-library-bug) with semantic-release trying to learn it but don't understand how its release commits work at all.

Here's my config in package.json

```json
 "release": {
  "npmPublish": false,
  "verifyConditions": [
   "@semantic-release/github"
  ],
  "prepare": [
   "@semantic-release/npm",
   {
    "path": "@semantic-release/git",
    "assets": [
     "package.json",
     "yarn.lock",
     "dist/**/*.{js|css}"
    ]
   }
  ],
  "publish": [
   "@semantic-release/github"
  ]
 }
```

I'm using circleci and have this as my build:
```yml
      - run: yarn test
      - run: yarn build # babel src/ -d dist/
      - run: yarn run semantic-release
      - run: git status
      - run: git log -1 --name-only
```

For my test, I'm editing the `src/index.js`, not touching `dist/index.js` file, and committing that so the build will happen on circle and a new version will be published with the updated `dist`. 

I see this in circleci output for `git status`(which happens _after_ `semantic-release` runs):

```
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dist/index.js

no changes added to commit (use "git add" and/or "git commit -a")
```

The `git log -1 --name-only` command shows this: 

```
git log -1 --name-only
commit b8b72510cedec12443ab4b46e848b0198429ea6c
Author: semantic-release-bot <semantic-release-bot@martynus.net>
Date:   Mon Jul 23 01:40:35 2018 +0000

    chore(release): 2.4.0 [skip ci]
    
    # [2.4.0](https://github.com/dadamssg/react-testing-library-bug/compare/v2.3.1...v2.4.0) (2018-07-23)
    
    ### Features
    
    * **code:** blah test ([06571d4](https://github.com/dadamssg/react-testing-library-bug/commit/06571d4))

package.json
```

Somehow though, this commit gets published to github even though it shows it's not been pushed _after_ semantic-release has run.

So my questions are:

- Why isn't my built `dist` output being included in the release commit? 
- How is this commit finding its way to github after semantic-release has run and git shows it's not been pushed???

**Comment by pvdlg** [comment]
> Why isn't my built dist output being included in the release commit?

Because your glob `dist/**/*.{js|css}` is invalid. The valid glob you want is `dist/**/*.{js,css}`.
Actually, you have a very similar [example](https://github.com/semantic-release/git#assets-examples) in the documentation:
> `[['dist/**/*.{js,css}', '!**/*.min.*']]`: include all `js` and `css` files in the `dist` directory and its sub-directories excluding the minified version.

> How is this commit finding its way to github after semantic-release has run and git shows it's not been pushed???

That's probably because  of the way CircleCI works. I guess you have different steps that runs on different jobs/containers. semantic-release create run on a given job/container and commit/push to the remote. Then Circle CI run the following things in your build on different jobs/container but they don't update the cloned repo there.
CircleCI should share the filesystem on which the clone repo is, so if a job/container modifies it the other can see it. Maybe there is a way to configure that.
If circleCI doesn't support that, you can manually run `git fetch` on each job/container that runs after the one running semantic-release.

**Comment by dadamssg** [comment]
Ah, that makes sense about circle. Thanks!

So the [Usage](devMode ? 'style-loader' : MiniCssExtractPlugin.loader) section has a typo? That's where i got the glob syntax.

**Comment by pvdlg** [comment]
Indeed, good catch! I'm fixing that right away!
