### ISSUE TITLE
Create a general means of publishing to any git repository

### ISSUE THREAD

**Issue by MartinMuzatko** [semantic-release/git#80]
Is there a general means to `publish` to any git repository?
This is a very important option.
Right now, there are only hooks to `verify` and `prepare`

**Comment by pvdlg** [comment]
What does "means to publish to any git repository" means? What command would you run to achieve that? What would be the benefit.

This plugin creates a commit with some files during the `prepare` step because semantic-release creates a tag after the `prepare` phase and before the `publish` one. So the commit created by this plugin has to be tagged, therefore it's created in the `prepare` phase. This is why there is no `publish` step.

**Comment by MartinMuzatko** [comment]
`publish` does nothing more than actually pushing the commit - I know.
So if no plugin is available for my git repo hoster, I just need to execute `git push`?

**Comment by pvdlg** [comment]
> publish does nothing more than actually pushing the commit - right?

As explained in the previous comment, there is no `publish` step for this plugin. 

> So if no plugin is available for my git repo hoster, I just need to execute git push?
What do you mean by "no plugin is available for my git repo hoster"?

Are you reporting an issue with this plugin? If yes what is the problem? Please describe what's happening and you expect to happen.
If you are asking for a new feature, please describe in detail what you expect to happen, with as many details as possible.
